### ISSUE TITLE
build error 

### ISSUE THREAD

**Issue by tatsuiman** [malice-plugins/kibana-plugin-builder#1]
```
$ docker run --init --rm -ti -v `pwd`:/plugin -w /plugin blacktop/kibana-plugin-builder node kibana/scripts/generate_plugin --help
module.js:549
    throw err;
    ^

Error: Cannot find module '/plugin/kibana/scripts/generate_plugin'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
```

**Comment by blacktop** [comment]
I think you need to bootstrap first to pull down all the node deps

**Comment by blacktop** [comment]
This will work:

```
$ mkdir my-new-plugin
$ docker run --init -it --rm \
             -w /plugin \
             -v `pwd`/my-new-plugin:/plugin/kibana-extra \
             blacktop/kibana-plugin-builder new-plugin hotness
```
